# Generated by Django 2.0.6 on 2019-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=30)),
                ('profile', models.FileField(blank='true', upload_to='Profile_image/')),
            ],
        ),
    ]
