# Generated by Django 2.0.6 on 2019-03-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject2ndYEar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'II year',
            },
        ),
        migrations.CreateModel(
            name='Subject3rdYEar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'III year',
            },
        ),
        migrations.CreateModel(
            name='Subject4thYEar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'IV year',
            },
        ),
    ]
