# Generated by Django 2.0.6 on 2019-03-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Add_Subject', '0001_initial'),
        ('User_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IIIYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_details.SignUp')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Subject.Subject3rdYEar')),
            ],
            options={
                'verbose_name': 'III Year',
            },
        ),
        migrations.CreateModel(
            name='IIYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_details.SignUp')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Subject.Subject2ndYEar')),
            ],
            options={
                'verbose_name': 'II Year',
            },
        ),
        migrations.CreateModel(
            name='IVYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User_details.SignUp')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Subject.Subject4thYEar')),
            ],
            options={
                'verbose_name': 'IV Year',
            },
        ),
    ]
