# Generated by Django 2.0.6 on 2019-03-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_details', '0001_initial'),
        ('Add_Lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IIIYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Lab.Lab3rdYEar')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='III_Year_Teacher_set', to='User_details.SignUp')),
            ],
            options={
                'verbose_name': 'III Year',
            },
        ),
        migrations.CreateModel(
            name='IIYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Lab.Lab2ndYEar')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='II_year_Lab_set', to='User_details.SignUp')),
            ],
            options={
                'verbose_name': 'II Year',
            },
        ),
        migrations.CreateModel(
            name='IVYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture', models.PositiveIntegerField()),
                ('Lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Add_Lab.Lab4thYEar')),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IV_Year_Teacher_set', to='User_details.SignUp')),
            ],
            options={
                'verbose_name': 'IV Year',
            },
        ),
    ]
