# Generated by Django 2.0.6 on 2019-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('sub', models.CharField(max_length=50)),
                ('lecture', models.CharField(max_length=50)),
                ('summary', models.TextField()),
            ],
        ),
    ]
